#!/usr/bin/env bash

do_rewe() {
  rm -f filialen-rewe
  curl -sf 'https://secureservice.rewe.co.at/filialservice/FilialJson.asmx/GetFilialenJson?shopCd=%27BA%27&jp=cb' >> filialen-rewe
  curl -sf 'https://secureservice.rewe.co.at/filialservice/FilialJson.asmx/GetFilialenJson?shopCd=%27MS%27&jp=cb' >> filialen-rewe
  curl -sf 'https://secureservice.rewe.co.at/filialservice/FilialJson.asmx/GetFilialenJson?shopCd=%27BP%27&jp=cb' >> filialen-rewe
  curl -sf 'https://secureservice.rewe.co.at/filialservice/FilialJson.asmx/GetFilialenJson?shopCd=%27PE%27&jp=cb' >> filialen-rewe
  curl -sf 'https://secureservice.rewe.co.at/filialservice/FilialJson.asmx/GetFilialenJson?shopCd=%27SU%27&jp=cb' >> filialen-rewe
  curl -sf 'http://service.rewe.co.at/filialservice/FilialJson.asmx/GetFilialenJson?shopCd=%27AD%27&jp=cb' >> filialen-rewe
  node -e 'cb = require("./rewe.js").format_csv; require("./filialen-rewe");'
}

do_mth() {
  curl -sf 'https://www.libro.at/ustorelocator/location/search/?addr=%25' | xsltproc mth.xsl - | sed -e 's/^/LIBRO;/'
  curl -sf 'https://www.pagro.at/ustorelocator/location/search/?addr=%25' | xsltproc mth.xsl - | sed -e 's/^/PAGRO;/'
}

do_msb() {
  rm -f filialen-mediamarkt
  curl -sf 'http://www.mediamarkt.at/webapp/wcs/stores/servlet/MultiChannelAllStores?storeId=10201&langId=-15' >> filialen-mediamarkt
  echo 'exports.shops = customShopsList;' >> filialen-mediamarkt
  rm -f filialen-saturn
  curl -sf 'http://www.saturn.at/webapp/wcs/stores/servlet/MultiChannelAllStores?storeId=20301&langId=-15' >> filialen-saturn
  echo 'exports.shops = customShopsList;' >> filialen-saturn

  node -e 'format_csv = require("./msb.js").format_csv;
  shops=require("./filialen-mediamarkt").shops; format_csv("MEDIAMARKT", shops);
  shops=require("./filialen-saturn").shops; format_csv("SATURN", shops);
  '
}

do_zielpunkt() {
  rm -f filialen-zielpunkt
  echo 'cb(' >> filialen-zielpunkt
  curl -sf 'http://www.zielpunkt.at/data/filalen3.php' >> filialen-zielpunkt
  echo ');' >> filialen-zielpunkt
  node -e 'cb=require("./zielpunkt.js").format_csv; require("./filialen-zielpunkt");'
}

echo 'STORETYPE;STOREID;LAT;LON;REGION;ZIP;CITY;ADDRESS'
do_msb
do_mth
do_rewe
do_zielpunkt
